services:
  db:
    image: postgres:18.1-alpine3.22
    container_name: bhasasuraksha-postgres
    environment:
      POSTGRES_USER: bhashafrontend
      POSTGRES_PASSWORD: suraksha
      POSTGRES_DB: bhashafrontenddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
